image: maven:3.6.1-jdk-8

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - bash configure-maven.sh
          - export IMAGE_NAME=docker.io/bigconsultancy/distil-integrations:latest
          - docker build -t $IMAGE_NAME .
          - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          - docker push $IMAGE_NAME

options:
  docker: true

definitions:
  services:
    docker:
      memory: 3072