#spring.datasource:
#  url: jdbc:postgresql://distil-staging-postgres.postgres.database.azure.com:5432/distil?searchpath=integrations
#  username: distil_admin@distil-staging-postgres
#  password: "!qaz2wsXX"
#  driver-class-name: org.postgresql.Driver
#
#cassandra:
#  servers:
#    #   todo deal with local network setup
#    - 40.127.201.110
#  keyspace: distil
#  accountKeyspaceReplicationOptions:
#    class: SimpleStrategy
#    replication_factor: 1
#
#ai:
#  distil:
#    api:
#      integrations:
#        url: https://distil-staging-integrations.azurewebsites.net
#      internal:
#        url: https://distil-staging-api.azurewebsites.net
#
#server:
#  port: 80

spring.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/distil?searchpath=distil
  username: postgres
  password: 1qaz2wsXX

cassandra:
  servers:
    - 10.1.3.5
  keyspace: distil
  accountKeyspaceReplicationOptions:
    class: SimpleStrategy
    replication_factor: 1

ai:
  distil:
    api:
      integrations:
        url: http://localhost:8889
      internal:
        url: http://localhost:8888

server:
  port: 8889
