spring.datasource:
  url: jdbc:postgresql://localhost:5432/distil?searchpath=integrations
  username: postgres
  password: 1qaz2wsXX
  driver-class-name: org.postgresql.Driver

cassandra:
  servers:
    - localhost
  keyspace: distil
  accountKeyspaceReplicationOptions:
    class: SimpleStrategy
    replication_factor: 1

ai:
  distil:
    api:
      integrations:
        url: http://localhost:8087
      internal:
        url: http://localhost:8086
      public:
        url: http://localhost:8088/public/{org}/{api-code}/customerId

server:
  port: 8087

ai.distil.datapipeline: '{
  cmo: "http://localhost:8090",
  crowdfunder: "http://localhost:8091",
  crowdcube: "http://localhost:8092"
}'
