spring:
  main.banner-mode: 'off'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        default_schema: integrations
        temp.use_jdbc_metadata_defaults: false
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  flyway:
    schemas: integrations

app:
  name: distil_integration

logging.level.org.springframework: ERROR

ai.distil.integrations.connections:
  http:
    mailChimp:
      baseUrl: https://%s.api.mailchimp.com/3.0
    campaignMonitor:
      baseUrl: https://api.createsend.com/api/v3.2
    salesforce:
      baseUrl: https://login.salesforce.com
      apiVersion: v46.0

  jdbc:
    mySql:
      protocol: mysql
      props: "?useReadAheadInput=false&useFastDateParsing=false&zeroDateTimeBehavior=convertToNull&useCursorFetch=true"
    postgreSql:
      protocol: postgresql
      props: ""
    msSql:
      protocol: sqlserver
      props: ";integratedSecurity=true"
    redshift:
      protocol: redshift
      props: ""

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

spring.datasource:
  url: jdbc:postgresql://distil-staging-postgres.postgres.database.azure.com:5432/distil?searchpath=integrations
  username: distil_admin@distil-staging-postgres
  password: "!qaz2wsXX"
  driver-class-name: org.postgresql.Driver

cassandra:
  servers:
#   todo deal with local network setup
    - 40.127.201.110
  keyspace: distil
  accountKeyspaceReplicationOptions:
    class: SimpleStrategy
    replication_factor: 1

ai:
  distil:
    api:
      integrations:
        url: https://distil-integrations.azurewebsites.net
      internal:
        url: http://localhost:8086

server:
  port: 80