spring:
  profiles.active: local
  main.banner-mode: 'off'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        default_schema: integrations
        temp.use_jdbc_metadata_defaults: false
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  flyway:
    schemas: integrations

spring.datasource:
  url: jdbc:postgresql://distil-postgresql.postgres.database.azure.com:5432/distil?searchpath=distil
  username: distilAdmin@distil-postgresql
  password: 1qaz2wsXX
  driver-class-name: org.postgresql.Driver

cassandra:
  servers:
    - 10.2.2.4
    - 10.2.2.5
    - 10.2.2.6
  keyspace: distil_app
  accountKeyspaceReplicationOptions:
    class: SimpleStrategy
    replication_factor: 1

ai:
  distil:
    api:
      integrations:
        url: http://40.127.201.179:8889
      internal:
        url: http://40.127.201.179:8888

app:
  name: distil_integration

logging.level.org.springframework: ERROR

server:
  port: 8889

ai.distil.integrations.connections:
  mySql:
    protocol: mysql
    props: "?useReadAheadInput=false&useFastDateParsing=false&zeroDateTimeBehavior=convertToNull&useCursorFetch=true"
  postgreSql:
    protocol: postgresql
    props: ""
  msSql:
    protocol: sqlserver
    props: ";integratedSecurity=true"
  redshift:
    protocol: redshift
    props: ""