spring.datasource:
  url: jdbc:postgresql://localhost:5433/distil_dev?searchpath=integrations
  username: postgres
  password: 1qaz2wsXX
  driver-class-name: org.postgresql.Driver

cassandra:
  servers:
    - localhost
  keyspace: system
  accountKeyspaceReplicationOptions:
    class: SimpleStrategy
    replication_factor: 1

ai:
  distil:
    integrations:
      app:
        maxDataSourceSize: -1
    api:
      integrations:
        url: http://localhost:8087
      internal:
        url: http://localhost:8086
      public:
        url: http://localhost:8088/public/{org}/{api-code}/customerId

server:
  port: 8087