spring.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/distil?searchpath=distil
  username: postgres
  password: 1qaz2wsXX

cassandra:
  servers:
    - 10.1.3.5
  keyspace: distil
  accountKeyspaceReplicationOptions:
    class: SimpleStrategy
    replication_factor: 1

ai:
  distil:
    api:
      integrations:
        url: http://localhost:8889
      internal:
        url: http://localhost:8888

server:
  port: 8889