version: '3'
services:
  integrations:
    image: distil.azurecr.io/distil-integrations-development:latest
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      DEFAULT_PROFILE: staging