spring:
  profiles.active: local
  main.banner-mode: 'off'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        default_schema: integrations
        temp.use_jdbc_metadata_defaults: false
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  flyway:
    schemas: integrations

app:
  name: distil_integration

logging.level.org.springframework: ERROR

ai.distil.integrations:
  app:
    maxDataSourceSize: -1
  connections:
    http:
      mailChimp:
        baseUrl: https://%s.api.mailchimp.com/3.0
      klaviyo:
        baseUrl: https://a.klaviyo.com
      campaignMonitor:
        baseUrl: https://api.createsend.com/api/v3.2
      salesforce:
        baseUrl: https://login.salesforce.com
        apiVersion: v46.0
    jdbc:
      mySql:
        protocol: mysql
        props: "?useReadAheadInput=false&useFastDateParsing=false&zeroDateTimeBehavior=convertToNull&useCursorFetch=true"
      postgreSql:
        protocol: postgresql
        props: ""
      msSql:
        protocol: sqlserver
        props: ";integratedSecurity=true"
      redshift:
        protocol: redshift
        props: ""

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
